-- Удаляем старые группы товаров
DELETE FROM reference_data WHERE category = 'product_group';

-- Вставляем группы товаров с кодами из списка
INSERT INTO reference_data (category, code, value, label, sort_order) VALUES
('product_group', '001', 'verxnyaya_odezhda_dlya_devochek', 'Верхняя одежда для девочек', 1),
('product_group', '002', 'verxnyaya_odezhda_dlya_malchikov', 'Верхняя одежда для мальчиков', 2),
('product_group', '003', 'verxnyaya_odezhda_dlya_novorozhdennyx', 'Верхняя одежда для новорожденных', 3),
('product_group', '004', 'bryuki_kapri_shorty_yubki_dlya_devochek', 'Брюки, капри, шорты, юбки для девочек', 4),
('product_group', '005', 'bryuki_kapri_shorty_dlya_malchikov', 'Брюки, капри, шорты для мальчиков', 5),
('product_group', '006', 'bryuki_kapri_shorty_dlya_novorozhdennyx', 'Брюки, капри, шорты для новорожденных', 6),
('product_group', '007', 'platya_sarafany_dlya_devochek', 'Платья, сарафаны для девочек', 7),
('product_group', '008', 'platya_sarafany_dlya_novorozhdennyx', 'Платья, сарафаны для новорожденных', 8),
('product_group', '009', 'bluzki_rubashki_futbolki_vodolazki_topy_dlya_devochek', 'Блузки, рубашки, футболки, водолазки, топы для девочек', 9),
('product_group', '010', 'bluzki_rubashki_futbolki_vodolazki_topy_dlya_malchikov', 'Блузки, рубашки, футболки, водолазки, топы для мальчиков', 10),
('product_group', '011', 'bluzki_rubashki_futbolki_vodolazki_topy_dlya_novorozhdennyx', 'Блузки, рубашки, футболки, водолазки, топы для новорожденных', 11),
('product_group', '012', 'trikotazhnye_izdeliya_dlya_devochek', 'Трикотажные изделия для девочек', 12),
('product_group', '013', 'trikotazhnye_izdeliya_dlya_malchikov', 'Трикотажные изделия для мальчиков', 13),
('product_group', '014', 'trikotazhnye_izdeliya_dlya_novorozhdennyx', 'Трикотажные изделия для новорожденных', 14),
('product_group', '015', 'detskoe_nizhnee_bele', 'Детское нижнее белье', 15),
('product_group', '016', 'detskie_chulochno_nosochnye_izdeliya', 'Детские чулочно-носочные изделия', 16),
('product_group', '017', 'detskie_golovnye_ubory', 'Детские головные уборы', 17),
('product_group', '018', 'detskie_perchatki_varezhki_sharfy_palantiny', 'Детские перчатки, варежки, шарфы, палантины', 18),
('product_group', '019', 'detskie_platochnye_izdeliya', 'Детские платочные изделия', 19),
('product_group', '020', 'detskaya_obuv_s_verxom_iz_kozhi_dlya_devochek', 'Детская обувь с верхом из кожи для девочек', 20),
('product_group', '021', 'detskaya_obuv_s_verxom_iz_kozhi_dlya_malchikov', 'Детская обувь с верхом из кожи для мальчиков', 21),
('product_group', '022', 'detskaya_obuv_s_verxom_iz_tekstilnyx_materialov_dlya_devochek', 'Детская обувь с верхом из текстильных материалов для девочек', 22),
('product_group', '023', 'detskaya_obuv_s_verxom_iz_tekstilnyx_materialov_dlya_malchikov', 'Детская обувь с верхом из текстильных материалов для мальчиков', 23),
('product_group', '024', 'detskaya_obuv_s_verxom_iz_polimernyx_materialov_dlya_devochek', 'Детская обувь с верхом из полимерных материалов для девочек', 24),
('product_group', '025', 'detskaya_obuv_s_verxom_iz_polimernyx_materialov_dlya_malchikov', 'Детская обувь с верхом из полимерных материалов для мальчиков', 25),
('product_group', '026', 'sportivnaya_detskaya_obuv_dlya_devochek', 'Спортивная детская обувь для девочек', 26),
('product_group', '027', 'sportivnaya_detskaya_obuv_dlya_malchikov', 'Спортивная детская обувь для мальчиков', 27),
('product_group', '028', 'domashnaya_detskaya_obuv_dlya_devochek', 'Домашняя детская обувь для девочек', 28),
('product_group', '029', 'domashnaya_detskaya_obuv_dlya_malchikov', 'Домашняя детская обувь для мальчиков', 29),
('product_group', '030', 'paltovaya_gruppa_dlya_devochek', 'Пальтовая группа для девочек', 30),
('product_group', '031', 'paltovaya_gruppa_dlya_malchikov', 'Пальтовая группа для мальчиков', 31),
('product_group', '032', 'paltovaya_gruppa_dlya_novorozhdennyx', 'Пальтовая группа для новорожденных', 32),
('product_group', '033', 'kostyumnaya_gruppa_dlya_devochek', 'Костюмная группа для девочек', 33),
('product_group', '034', 'kostyumnaya_gruppa_dlya_malchikov', 'Костюмная группа для мальчиков', 34),
('product_group', '035', 'kostyumnaya_gruppa_dlya_novorozhdennyx', 'Костюмная группа для новорожденных', 35),
('product_group', '036', 'detskie_sumki', 'Детские сумки', 36),
('product_group', '037', 'detskie_ryukzaki', 'Детские рюкзаки', 37),
('product_group', '038', 'detskie_remni', 'Детские ремни', 38),
('product_group', '039', 'futbolki_detskie_dlya_devochek', 'Футболки детские для девочек', 39),
('product_group', '040', 'futbolki_detskie_dlya_malchikov', 'Футболки детские для мальчиков', 40),
('product_group', '041', 'futbolki_detskie_dlya_novorozhdennyx', 'Футболки детские для новорожденных', 41),
('product_group', '042', 'xudi_svitery_tolstovki_kofty_dlya_devochek', 'Худи, свитеры, толстовки, кофты для девочек', 42),
('product_group', '043', 'xudi_svitery_tolstovki_kofty_dlya_malchikov', 'Худи, свитеры, толстовки, кофты для мальчиков', 43),
('product_group', '044', 'xudi_svitery_tolstovki_kofty_dlya_novorozhdennyx', 'Худи, свитеры, толстовки, кофты для новорожденных', 44),
('product_group', '045', 'verxnyaya_odezhda_dlya_zhenshhin', 'Верхняя одежда для женщин', 45),
('product_group', '046', 'verxnyaya_odezhda_dlya_muzhchin', 'Верхняя одежда для мужчин', 46),
('product_group', '047', 'bryuki_dzhinsy_shorty_kapri_leginsy_dlya_zhenshhin', 'Брюки, джинсы, шорты, капри, легинсы для женщин', 47),
('product_group', '048', 'bryuki_dzhinsy_shorty_kapri_dlya_muzhchin', 'Брюки, джинсы, шорты, капри для мужчин', 48),
('product_group', '049', 'platya_sarafany_tuniky_dlya_zhenshhin', 'Платья, сарафаны, туники для женщин', 49),
('product_group', '050', 'yubki_dlya_zhenshhin', 'Юбки для женщин', 50),
('product_group', '051', 'bluzki_rubashki_topy_futbolki_vodolazki_dlya_zhenshhin', 'Блузки, рубашки, топы, футболки, водолазки для женщин', 51),
('product_group', '052', 'bluzki_rubashki_topy_futbolki_vodolazki_dlya_muzhchin', 'Блузки, рубашки, топы, футболки, водолазки для мужчин', 52),
('product_group', '053', 'trikotazhnye_izdeliya_dlya_zhenshhin', 'Трикотажные изделия для женщин', 53),
('product_group', '054', 'trikotazhnye_izdeliya_dlya_muzhchin', 'Трикотажные изделия для мужчин', 54),
('product_group', '055', 'nizhnee_bele_dlya_zhenshhin', 'Нижнее белье для женщин', 55),
('product_group', '056', 'nizhnee_bele_dlya_muzhchin', 'Нижнее белье для мужчин', 56),
('product_group', '057', 'chulochno_nosochnye_izdeliya_dlya_zhenshhin', 'Чулочно-носочные изделия для женщин', 57),
('product_group', '058', 'chulochno_nosochnye_izdeliya_dlya_muzhchin', 'Чулочно-носочные изделия для мужчин', 58),
('product_group', '059', 'golovnye_ubory_dlya_zhenshhin', 'Головные уборы для женщин', 59),
('product_group', '060', 'golovnye_ubory_dlya_muzhchin', 'Головные уборы для мужчин', 60),
('product_group', '061', 'perchatki_varezhki_sharfy_palantiny_dlya_zhenshhin', 'Перчатки, варежки, шарфы, палантины для женщин', 61),
('product_group', '062', 'perchatki_varezhki_sharfy_dlya_muzhchin', 'Перчатки, варежки, шарфы для мужчин', 62),
('product_group', '063', 'platochnye_izdeliya_dlya_zhenshhin', 'Платочные изделия для женщин', 63),
('product_group', '064', 'zhenskie_sumki', 'Женские сумки', 64),
('product_group', '065', 'muzhskie_sumki', 'Мужские сумки', 65),
('product_group', '066', 'ryukzaki_dlya_zhenshhin', 'Рюкзаки для женщин', 66),
('product_group', '067', 'ryukzaki_dlya_muzhchin', 'Рюкзаки для мужчин', 67),
('product_group', '068', 'aksessuary_dlya_volos_ukrasheniya', 'Аксессуары для волос, украшения', 68),
('product_group', '069', 'ochki_solncezashchitnye', 'Очки солнцезащитные', 69),
('product_group', '070', 'breloki', 'Брелоки', 70),
('product_group', '071', 'zontiki', 'Зонтики', 71),
('product_group', '072', 'koshelki_klatch_barsetki_dlya_zhenshhin', 'Кошельки, клатч, барсетки для женщин', 72),
('product_group', '073', 'koshelki_klatch_barsetki_dlya_muzhchin', 'Кошельки, клатч, барсетки для мужчин', 73),
('product_group', '074', 'remni_poyasa_podtyazhki_dlya_zhenshhin', 'Ремни, пояса, подтяжки для женщин', 74),
('product_group', '075', 'remni_poyasa_podtyazhki_dlya_muzhchin', 'Ремни, пояса, подтяжки для мужчин', 75),
('product_group', '076', 'obuv_s_verxom_iz_kozhi_dlya_zhenshhin', 'Обувь с верхом из кожи для женщин', 76),
('product_group', '077', 'obuv_s_verxom_iz_kozhi_dlya_muzhchin', 'Обувь с верхом из кожи для мужчин', 77),
('product_group', '078', 'obuv_s_verxom_iz_iskusstvennoj_kozhi_dlya_zhenshhin', 'Обувь с верхом из искусственной кожи для женщин', 78),
('product_group', '079', 'obuv_s_verxom_iz_iskusstvennoj_kozhi_dlya_muzhchin', 'Обувь с верхом из искусственной кожи для мужчин', 79),
('product_group', '080', 'obuv_s_verxom_iz_tekstilnyx_materialov_dlya_zhenshhin', 'Обувь с верхом из текстильных материалов для женщин', 80),
('product_group', '081', 'obuv_s_verxom_iz_tekstilnyx_materialov_dlya_muzhchin', 'Обувь с верхом из текстильных материалов для мужчин', 81),
('product_group', '082', 'obuv_s_verxom_iz_polimernyx_materialov_dlya_zhenshhin', 'Обувь с верхом из полимерных материалов для женщин', 82),
('product_group', '083', 'obuv_s_verxom_iz_polimernyx_materialov_dlya_muzhchin', 'Обувь с верхом из полимерных материалов для мужчин', 83),
('product_group', '084', 'sportivnaya_obuv_dlya_zhenshhin', 'Спортивная обувь для женщин', 84),
('product_group', '085', 'sportivnaya_obuv_dlya_muzhchin', 'Спортивная обувь для мужчин', 85),
('product_group', '086', 'domashnaya_obuv_dlya_zhenshhin', 'Домашняя обувь для женщин', 86),
('product_group', '087', 'domashnaya_obuv_dlya_muzhchin', 'Домашняя обувь для мужчин', 87),
('product_group', '088', 'kurtki_vetrovki_parki_dlya_zhenshhin', 'Куртки, ветровки, парки для женщин', 88),
('product_group', '089', 'kurtki_vetrovki_parki_dlya_muzhchin', 'Куртки, ветровки, парки для мужчин', 89),
('product_group', '090', 'puxoviki_dlinye_dlya_zhenshhin', 'Пуховики длинные для женщин', 90),
('product_group', '091', 'puxoviki_dlinye_dlya_muzhchin', 'Пуховики длинные для мужчин', 91),
('product_group', '092', 'puxoviki_korotkie_dlya_zhenshhin', 'Пуховики короткие для женщин', 92),
('product_group', '093', 'puxoviki_korotkie_dlya_muzhchin', 'Пуховики короткие для мужчин', 93),
('product_group', '094', 'zhilety_uteplennye_bezrukavki_dlya_zhenshhin', 'Жилеты утепленные, безрукавки для женщин', 94),
('product_group', '095', 'zhilety_uteplennye_bezrukavki_dlya_muzhchin', 'Жилеты утепленные, безрукавки для мужчин', 95),
('product_group', '096', 'plashchi_palto_shubki_zhakety_dlya_zhenshhin', 'Плащи, пальто, шубки, жакеты для женщин', 96),
('product_group', '097', 'plashchi_palto_shubki_zhakety_dlya_muzhchin', 'Плащи, пальто, шубки, жакеты для мужчин', 97),
('product_group', '098', 'paltovaya_gruppa_dlya_zhenshhin', 'Пальтовая группа для женщин', 98),
('product_group', '099', 'paltovaya_gruppa_dlya_muzhchin', 'Пальтовая группа для мужчин', 99),
('product_group', '100', 'kostyumnaya_gruppa_dlya_zhenshhin', 'Костюмная группа для женщин', 100),
('product_group', '101', 'kostyumnaya_gruppa_dlya_muzhchin', 'Костюмная группа для мужчин', 101),
('product_group', '102', 'xudi_tolstovki_svitery_kofty_kardigany_dlya_zhenshhin', 'Худи, толстовки, свитеры, кофты, кардиганы для женщин', 102),
('product_group', '103', 'xudi_tolstovki_svitery_kofty_kardigany_dlya_muzhchin', 'Худи, толстовки, свитеры, кофты, кардиганы для мужчин', 103),
('product_group', '104', 'futbolki_vodolazki_longsliv_polo_dlya_zhenshhin', 'Футболки, водолазки, лонгслив, поло для женщин', 104),
('product_group', '105', 'futbolki_vodolazki_longsliv_polo_dlya_muzhchin', 'Футболки, водолазки, лонгслив, поло для мужчин', 105),
('product_group', '106', 'kombinezon_dlya_devochek', 'Комбинезон для девочек', 106),
('product_group', '107', 'kombinezon_dlya_malchikov', 'Комбинезон для мальчиков', 107),
('product_group', '108', 'kombinezon_dlya_novorozhdennyx', 'Комбинезон для новорожденных', 108),
('product_group', '109', 'polukombinezony_dlya_devochek', 'Полукомбинезоны для девочек', 109),
('product_group', '110', 'polukombinezony_dlya_malchikov', 'Полукомбинезоны для мальчиков', 110),
('product_group', '111', 'polukombinezony_dlya_novorozhdennyx', 'Полукомбинезоны для новорожденных', 111),
('product_group', '112', 'aksessuary_k_detskoj_obuvi', 'Аксессуары к детской обуви', 112),
('product_group', '113', 'aksessuary_k_vzrosloj_obuvi', 'Аксессуары к взрослой обуви', 113),
('product_group', '114', 'detskie_steganye_izdeliya', 'Детские стеганые изделия', 114),
('product_group', '115', 'steganye_izdeliya_dlya_zhenshhin', 'Стеганые изделия для женщин', 115),
('product_group', '116', 'steganye_izdeliya_dlya_muzhchin', 'Стеганые изделия для мужчин', 116),
('product_group', '117', 'chemodany_dorozhnye_sumki', 'Чемоданы, дорожные сумки', 117),
('product_group', '118', 'termokruzhki', 'Термокружки', 118),
('product_group', '119', 'bytovaya_texnika', 'Бытовая техника', 119),
('product_group', '120', 'sportivnye_tovary', 'Спортивные товары', 120),
('product_group', '121', 'elektronnye_ustrojstva', 'Электронные устройства', 121),
('product_group', '122', 'tovary_dlya_doma', 'Товары для дома', 122),
('product_group', '123', 'tovary_dlya_detej', 'Товары для детей', 123),
('product_group', '124', 'igrushki', 'Игрушки', 124),
('product_group', '125', 'shkolnye_tovary', 'Школьные товары', 125),
('product_group', '126', 'krasota_i_zdorove', 'Красота и здоровье', 126),
('product_group', '127', 'produkty_pitaniya', 'Продукты питания', 127),
('product_group', '128', 'napitki', 'Напитки', 128),
('product_group', '129', 'tovary_dlya_zhivotnyx', 'Товары для животных', 129),
('product_group', '130', 'avto_moto_tovary', 'Авто-мото товары', 130),
('product_group', '131', 'sad_ogorod', 'Сад, огород', 131),
('product_group', '132', 'stroitelnye_materialy', 'Строительные материалы', 132),
('product_group', '133', 'instrumenty', 'Инструменты', 133),
('product_group', '134', 'knigi_zhurnaly', 'Книги, журналы', 134),
('product_group', '135', 'kantselyarskie_tovary', 'Канцелярские товары', 135),
('product_group', '136', 'upakovka_upakovochnye_materialy', 'Упаковка, упаковочные материалы', 136),
('product_group', '137', 'suveniry_podarki', 'Сувениры, подарки', 137),
('product_group', '138', 'prazdnichnye_tovary', 'Праздничные товары', 138),
('product_group', '139', 'oxota_rybalka_turizm', 'Охота, рыбалка, туризм', 139),
('product_group', '140', 'muzykalnye_instrumenty', 'Музыкальные инструменты', 140),
('product_group', '141', 'xobbi_tvorchestvo', 'Хобби, творчество', 141),
('product_group', '142', 'antikvar_kollekcionirovanie', 'Антиквар, коллекционирование', 142),
('product_group', '143', 'uslugi', 'Услуги', 143),
('product_group', '144', 'drugoe', 'Другое', 144)
ON CONFLICT (category, value) DO UPDATE SET
  code = EXCLUDED.code,
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order;
