-- Удаляем старые группы товаров
DELETE FROM reference_data WHERE category = 'product_group';

-- Вставляем исправленные группы товаров (отсортированные в алфавитном порядке)
INSERT INTO reference_data (category, code, value, label, sort_order) VALUES
('product_group', '201', 'beysbolka_detskaya_devochki', 'Бейсболка детская для девочек', 1),
('product_group', '202', 'beysbolka_detskaya_malchiki', 'Бейсболка детская для мальчиков', 2),
('product_group', '307', 'bluzka_detskaya_devochki', 'Блузка детская для девочек', 3),
('product_group', '306', 'bluzka_korotkiy_rukav_devochki', 'Блузка короткий рукав детская для девочек', 4),
('product_group', '361', 'bluzka_korotkiy_rukav_shkolnaya_devochki', 'Блузка с коротким рукавом школьная для девочек', 5),
('product_group', '355', 'bluzka_shkolnaya_devochki', 'Блузка школьная для девочек', 6),
('product_group', '567', 'bodi_dlinnyy_rukav_devochki', 'Боди с длинным рукавом для девочек', 7),
('product_group', '936', 'bodi_dlinnyy_rukav_malchiki', 'Боди с длинным рукавом для мальчиков', 8),
('product_group', '568', 'bodi_korotkiy_rukav_devochki', 'Боди с коротким рукавом для девочек', 9),
('product_group', '937', 'bodi_korotkiy_rukav_malchiki', 'Боди с коротким рукавом для мальчиков', 10),
('product_group', 'y54', 'bryuki_demisezonnye_devochki', 'Брюки демисезонные для девочек', 11),
('product_group', 'y53', 'bryuki_demisezonnye_malchiki', 'Брюки демисезонные для мальчика', 12),
('product_group', '527', 'bryuki_detskie_devochki', 'Брюки детские для девочек', 13),
('product_group', '553', 'bryuki_detskie_malchiki', 'Брюки детские для мальчиков', 14),
('product_group', 'a52', 'bryuki_letnie_devochki', 'Брюки летние для девочек', 15),
('product_group', '448', 'bryuki_sportivnye_uteplennye_devochki', 'Брюки спортивные утепленные для девочек', 16),
('product_group', '455', 'bryuki_sportivnye_uteplennye_malenkikh_devochek', 'Брюки спортивные утепленные для маленьких девочек', 17),
('product_group', '436', 'bryuki_sportivnye_uteplennye_malenkikh_malchikov', 'Брюки спортивные утепленные для маленьких мальчиков', 18),
('product_group', '435', 'bryuki_sportivnye_uteplennye_malchiki', 'Брюки спортивные утепленные для мальчиков', 19),
('product_group', '369', 'bryuki_shkolnye_malchiki', 'Брюки школьные для мальчиков', 20),
('product_group', '223', 'varezhki_detskie_devochki', 'Варежки детские для девочек', 21),
('product_group', '224', 'varezhki_detskie_malchiki', 'Варежки детские для мальчиков', 22),
('product_group', '954', 'vetrovka_detskaya_devochki', 'Ветровка детская для девочек', 23),
('product_group', '952', 'vetrovka_detskaya_malchiki', 'Ветровка детская для мальчиков', 24),
('product_group', 'y58', 'vetrovka_malenkikh_devochek', 'Ветровка для маленьких девочек', 25),
('product_group', 'y59', 'vetrovka_malenkikh_malchikov', 'Ветровка для маленьких мальчиков', 26),
('product_group', '535', 'vodolazka_detskaya_devochki', 'Водолазка детская для девочек', 27),
('product_group', '558', 'vodolazka_detskaya_malchiki', 'Водолазка детская для мальчиков', 28),
('product_group', 'a53', 'vyazanye_reytuzy_devochki', 'Вязаные рейтузы для девочек', 29),
('product_group', '565', 'galstuk_detskiy_malchiki', 'Галстук детский для мальчиков', 30),
('product_group', 'a68', 'galstuki_banty_devochki', 'Галстуки-банты для девочек', 31),
('product_group', '319', 'golfy_detskie_devochki', 'Гольфы детские для девочек', 32),
('product_group', '392', 'detskaya_letnyaya_shlyapa_devochki', 'Детская летняя шляпа для девочек', 33),
('product_group', '393', 'detskie_leginsy', 'Детские легинсы', 34),
('product_group', 'a51', 'detskie_leginsy_tri_chetverti', 'Детские легинсы три четверти', 35),
('product_group', '190', 'dzhemper_detskiy_devochki', 'Джемпер детский для девочек', 36),
('product_group', '189', 'dzhemper_detskiy_malchiki', 'Джемпер детский для мальчиков', 37),
('product_group', '912', 'dzhemper_malenkogo_malchika', 'Джемпер для маленького мальчика', 38),
('product_group', '911', 'dzhemper_malenkoy_devochki', 'Джемпер для маленькой девочки', 39),
('product_group', '181', 'dzhinsy_detskie_devochki', 'Джинсы детские для девочек', 40),
('product_group', '540', 'dzhinsy_detskie_uteplennye_devochki', 'Джинсы детские для девочек утепленные', 41),
('product_group', '182', 'dzhinsy_detskie_malchiki', 'Джинсы детские для мальчиков', 42),
('product_group', '860', 'dzhinsy_detskie_uteplennye_malchiki', 'Джинсы детские для мальчиков утепленные', 43),
('product_group', '942', 'dzhinsy_malenkogo_malchika', 'Джинсы для маленького мальчика', 44),
('product_group', '861', 'dzhinsy_malenkogo_malchika_uteplennye', 'Джинсы для маленького мальчика утепленные', 45),
('product_group', '943', 'dzhinsy_malenkoy_devochki', 'Джинсы для маленькой девочки', 46),
('product_group', '862', 'dzhinsy_malenkoy_devochki_uteplennye', 'Джинсы для маленькой девочки утепленные', 47),
('product_group', '242', 'dzhinsy_yunoshey', 'Джинсы для юношей', 48),
('product_group', 'a64', 'dozhdevik_detskiy_devochki', 'Дождевик детский для девочек', 49),
('product_group', 'a63', 'dozhdevik_detskiy_malchiki', 'Дождевик детский для мальчиков', 50),
('product_group', '886', 'zhilet_uteplennyy_devochki', 'Жилет утепленный детский для девочек', 51),
('product_group', '877', 'zhilet_uteplennyy_malchiki', 'Жилет утепленный детский для мальчиков', 52),
('product_group', '726', 'zhilet_uteplennyy_malenkogo_malchika', 'Жилет утепленный для маленького мальчика', 53),
('product_group', '727', 'zhilet_uteplennyy_malenkoy_devochki', 'Жилет утепленный для маленькой девочки', 54),
('product_group', '546', 'zhiletka_detskaya_devochki', 'Жилетка детская для девочек', 55),
('product_group', '563', 'zhiletka_detskaya_malchiki', 'Жилетка детская для мальчиков', 56),
('product_group', 'a56', 'zimniy_kombinezon_devochki', 'Зимний детский комбинезон для девочек', 57),
('product_group', 'a55', 'zimniy_kombinezon_malchiki', 'Зимний детский комбинезон для мальчиков', 58),
('product_group', 'a50', 'kapri_velosipedki_devochki', 'Капри и велосипедки для девочек', 59),
('product_group', '888', 'kardigan_detskiy_devochki', 'Кардиган детский для девочек', 60),
('product_group', '953', 'kardigan_detskiy_malchiki', 'Кардиган детский для мальчиков', 61),
('product_group', '705', 'karnavalnye_kostyumy_devochki', 'Карнавальные костюмы для девочек', 62),
('product_group', '720', 'karnavalnye_kostyumy_malchiki', 'Карнавальные костюмы для мальчиков', 63),
('product_group', '234', 'kolgotki_detskie_devochki', 'Колготки детские для девочек', 64),
('product_group', '235', 'kolgotki_detskie_malchiki', 'Колготки детские для мальчиков', 65),
('product_group', 'y51', 'kombinezon_demisezonnyy_devochki', 'Комбинезон демисезонный для девочек', 66),
('product_group', 'a72', 'kombinezon_demisezonnyy_malenkogo_malchika', 'Комбинезон демисезонный для маленького мальчика', 67),
('product_group', 'a71', 'kombinezon_demisezonnyy_malenkoy_devochki', 'Комбинезон демисезонный для маленькой девочки', 68),
('product_group', 'y52', 'kombinezon_demisezonnyy_malchiki', 'Комбинезон демисезонный для мальчика', 69),
('product_group', '938', 'kombinezon_malenkogo_malchika', 'Комбинезон для маленького мальчика', 70),
('product_group', '569', 'kombinezon_malenkoy_devochki', 'Комбинезон для маленькой девочки', 71),
('product_group', '570', 'kombinezon_novorozhdennykh_zimniy_devochki', 'Комбинезон для новорожденных зимний для девочек', 72),
('product_group', '896', 'kombinezon_novorozhdennykh_zimniy_malchiki', 'Комбинезон для новорожденных зимний для мальчиков', 73),
('product_group', '424', 'kombinezon_novorozhdennykh_uteplennyy', 'Комбинезон для новорожденных утепленный', 74),
('product_group', '305', 'kombinezon_letniy_devochki', 'Комбинезон летний детский для девочек', 75),
('product_group', '458', 'komplekt_kurtka_polukombinezon_devochki', 'Комплект для девочек: куртка зимняя и полукомбинезон', 76),
('product_group', '459', 'komplekt_kurtka_polukombinezon_malchiki', 'Комплект для мальчиков: куртка зимняя и полукомбинезон', 77),
('product_group', '698', 'komplekt_zimniy_malenkogo_malchika', 'Комплект зимней одежды для маленького мальчика', 78),
('product_group', '697', 'komplekt_zimniy_malenkoy_devochki', 'Комплект зимней одежды для маленькой девочки', 79),
('product_group', 'y49', 'komplekt_letney_odezhdy_devochki', 'Комплект летней одежды для девочки', 80),
('product_group', '962', 'komplekt_letney_odezhdy_malenkogo_malchika', 'Комплект летней одежды для маленького мальчика', 81),
('product_group', '961', 'komplekt_letney_odezhdy_malenkoy_devochki', 'Комплект летней одежды для маленькой девочки', 82),
('product_group', 'y50', 'komplekt_letney_odezhdy_malchiki', 'Комплект летней одежды для мальчиков', 83),
('product_group', '945', 'komplekt_odezhdy_malenkogo_malchika', 'Комплект одежды для маленького мальчика', 84),
('product_group', '944', 'komplekt_odezhdy_malenkoy_devochki', 'Комплект одежды для маленькой девочки', 85),
('product_group', '584', 'konvert_pelenaniya', 'Конверт для пеленания', 86),
('product_group', '882', 'kostyumy_zhakety_zhilety_devochki', 'Костюмы, жакеты и жилеты для девочек', 87),
('product_group', '875', 'kostyumy_pidzhaki_zhilety_malchiki', 'Костюмы, пиджаки и жилеты для мальчиков', 88),
('product_group', 'b36', 'kosynka_detskaya_devochki', 'Косынка детская для девочек', 89),
('product_group', '532', 'kosynka_detskaya_devochki_2', 'Косынка детская для девочек', 90),
('product_group', '297', 'kofta_detskaya_devochki', 'Кофта детская для девочек', 91),
('product_group', '557', 'kofta_detskaya_malchiki', 'Кофта детская для мальчиков', 92),
('product_group', '889', 'koftochka_malenkogo_malchika', 'Кофточка для маленького мальчика', 93),
('product_group', '571', 'koftochka_malenkoy_devochki', 'Кофточка для маленькой девочки', 94),
('product_group', '902', 'krestilnyy_nabor', 'Крестильный набор', 95),
('product_group', '313', 'kupalnik_detskiy', 'Купальник детский', 96),
('product_group', '200', 'kurtka_detskaya_devochki', 'Куртка детская для девочек', 97),
('product_group', '195', 'kurtka_detskaya_malchiki', 'Куртка детская для мальчиков', 98),
('product_group', '967', 'kurtka_dzhinsovaya_devochki', 'Куртка джинсовая для девочки', 99),
('product_group', '968', 'kurtka_dzhinsovaya_malchika', 'Куртка джинсовая для мальчика', 100),
('product_group', 'y56', 'kurtka_devochki_oblegchennaya', 'Куртка для девочек облегченная', 101),
('product_group', '948', 'kurtka_malenkikh_devochek', 'Куртка для маленьких девочек', 102),
('product_group', '949', 'kurtka_malenkikh_malchikov', 'Куртка для маленьких мальчиков', 103),
('product_group', 'y57', 'kurtka_malchiki_oblegchennaya', 'Куртка для мальчиков облегченная', 104),
('product_group', '885', 'kurtka_zimnyaya_devochki', 'Куртка зимняя детская для девочек', 105),
('product_group', '876', 'kurtka_zimnyaya_malchiki', 'Куртка зимняя детская для мальчиков', 106),
('product_group', '894', 'kurtka_zimnyaya_malenkikh_devochek', 'Куртка зимняя для маленьких девочек', 107),
('product_group', '895', 'kurtka_zimnyaya_malenkikh_malchikov', 'Куртка зимняя для маленьких мальчиков', 108),
('product_group', 'a57', 'letnee_platye_malenkoy_devochki', 'Летнее платье для маленькой девочки', 109),
('product_group', '985', 'lifchik_podrostkovyy', 'Лифчик подростковый', 110),
('product_group', '541', 'mayka_detskaya_devochki', 'Майка детская для девочек', 111),
('product_group', '561', 'mayka_detskaya_malchiki', 'Майка детская для мальчиков', 112),
('product_group', '950', 'mayka_malenkogo_malchika', 'Майка для маленького мальчика', 113),
('product_group', '899', 'mayka_malenkoy_devochki', 'Майка для маленькой девочки', 114),
('product_group', '318', 'nabor_lif_trusiki_devochki', 'Набор лиф и трусики детский для девочек', 115),
('product_group', '317', 'nabor_mayka_trusiki_devochki', 'Набор майка и трусики детский для девочек', 116),
('product_group', '025', 'nabor_trusy_mayka_malchiki', 'Набор трусы и майка детский для мальчиков', 117),
('product_group', '964', 'nabor_trusy_mayka_malenkoy_devochki', 'Набор трусы и майка для маленькой девочки', 118),
('product_group', '855', 'nabor_shapka_perchatki_devochki', 'Набор шапка и перчатки детские для девочек', 119),
('product_group', '856', 'nabor_shapka_perchatki_malchiki', 'Набор шапка и перчатки детские для мальчиков', 120),
('product_group', '221', 'nabor_shapka_sharf_devochki', 'Набор шапка и шарф детский для девочек', 121),
('product_group', '045', 'nabor_shapka_sharf_devochki_razmer', 'Набор шапка и шарф детский для девочек c размером', 122),
('product_group', '222', 'nabor_shapka_sharf_malchiki', 'Набор шапка и шарф детский для мальчиков', 123),
('product_group', '046', 'nabor_shapka_sharf_malchiki_razmer', 'Набор шапка и шарф детский для мальчиков с размером', 124),
('product_group', 'a75', 'novogodnyaya_odezhda_novorozhdennykh', 'Новогодняя одежда для новорожденных', 125),
('product_group', '173', 'noski_detskie_devochki', 'Носки детские для девочек', 126),
('product_group', '174', 'noski_detskie_malchiki', 'Носки детские для мальчиков', 127),
('product_group', '523', 'palto_zimnee_devochki', 'Пальто зимнее детское для девочек', 128),
('product_group', '530', 'panama_detskaya_devochki', 'Панама детская для девочек', 129),
('product_group', '554', 'panama_detskaya_malchiki', 'Панама детская для мальчиков', 130),
('product_group', '478', 'pelenki_tekstilnye', 'Пеленки текстильные', 131),
('product_group', '225', 'perchatki_detskie_devochki', 'Перчатки детские для девочек', 132),
('product_group', '226', 'perchatki_detskie_malchiki', 'Перчатки детские для мальчиков', 133),
('product_group', '231', 'pizhama_detskaya_devochki', 'Пижама детская для девочек', 134),
('product_group', '232', 'pizhama_detskaya_malchiki', 'Пижама детская для мальчиков', 135),
('product_group', 'a73', 'pizhama_detskaya_novogodnyaya', 'Пижама детская новогодняя', 136),
('product_group', '577', 'pinetki', 'Пинетки', 137),
('product_group', '312', 'plavki_detskie', 'Плавки детские', 138),
('product_group', '537', 'platye_vechernee_detskoe', 'Платье вечернее детское', 139),
('product_group', '438', 'platye_vyazanoe_devochki', 'Платье вязаное для девочек', 140),
('product_group', '238', 'platye_detskoe_devochki', 'Платье детское для девочек', 141),
('product_group', '299', 'platye_dlinnyy_rukav_devochki', 'Платье длинный рукав детское для девочек', 142),
('product_group', '890', 'platye_malenkoy_devochki', 'Платье для маленькой девочки', 143),
('product_group', '536', 'platye_letnee_detskoe', 'Платье летнее детское', 144),
('product_group', '925', 'platye_bodi', 'Платье-боди', 145),
('product_group', '956', 'plashch_detskiy_devochki', 'Плащ детский для девочек', 146),
('product_group', '891', 'podarochnyy_nabor_novorozhdennykh', 'Подарочный набор для новорожденных', 147),
('product_group', '904', 'podtyazhki_detskie', 'Подтяжки детские', 148),
('product_group', '572', 'polzunki_devochki', 'Ползунки для девочки', 149),
('product_group', '941', 'polzunki_malchika', 'Ползунки для мальчика', 150),
('product_group', '958', 'polukombinezon_malenkogo_malchika', 'Полукомбинезон для маленького мальчика', 151),
('product_group', '926', 'polukombinezon_malenkoy_devochki', 'Полукомбинезон для маленькой девочки', 152),
('product_group', '887', 'polukombinezon_zimniy_devochki', 'Полукомбинезон зимний детский для девочек', 153),
('product_group', '878', 'polukombinezon_zimniy_malchiki', 'Полукомбинезон зимний детский для мальчиков', 154),
('product_group', '574', 'raspashonka', 'Распашонка', 155),
('product_group', '947', 'romper_devochki', 'Ромпер для девочки', 156),
('product_group', '946', 'romper_malchika', 'Ромпер для мальчика', 157),
('product_group', '192', 'rubashka_detskaya_malchiki', 'Рубашка детская для мальчиков', 158),
('product_group', '308', 'rubashka_dlinnyy_rukav_malchiki', 'Рубашка длинный рукав детская для мальчиков', 159),
('product_group', '858', 'rubashka_malenkogo_malchika', 'Рубашка для маленького мальчика', 160),
('product_group', '406', 'rubashka_dlinnyy_rukav_shkolnaya_malchiki', 'Рубашка с длинным рукавом школьная для мальчиков', 161),
('product_group', '399', 'rubashka_korotkiy_rukav_shkolnaya_malchiki', 'Рубашка с коротким рукавом школьная для мальчиков', 162),
('product_group', '292', 'sarafan_detskiy_devochki', 'Сарафан детский для девочек', 163),
('product_group', '966', 'sarafan_dzhinsovyy_devochki', 'Сарафан джинсовый детский для девочек', 164),
('product_group', '963', 'sarafan_malenkoy_devochki', 'Сарафан для маленькой девочки', 165),
('product_group', '365', 'sarafany_platya_shkolnye_devochki', 'Сарафаны и платья школьные для девочек', 166),
('product_group', '240', 'sviter_detskiy_devochki', 'Свитер детский для девочек', 167),
('product_group', '241', 'sviter_detskiy_malchiki', 'Свитер детский для мальчиков', 168),
('product_group', 'a89', 'svitshot_devochki', 'Свитшот для девочки', 169),
('product_group', 'a91', 'svitshot_malchika', 'Свитшот для мальчика', 170),
('product_group', 'a90', 'svitshot_uteplennyy_devochki', 'Свитшот утепленный для девочки', 171),
('product_group', 'a92', 'svitshot_uteplennyy_malchiki', 'Свитшот утепленный для мальчика', 172),
('product_group', 'a29', 'sportivnaya_odezhda_devochki', 'Спортивная одежда для девочек', 173),
('product_group', 'a30', 'sportivnaya_odezhda_malchiki', 'Спортивная одежда для мальчиков', 174),
('product_group', '191', 'sportivnyy_kostyum_devochki', 'Спортивный костюм детский для девочек', 175),
('product_group', '239', 'sportivnyy_kostyum_malchiki', 'Спортивный костюм детский для мальчиков', 176),
('product_group', '709', 'termobele_devochki', 'Термобелье для девочек', 177),
('product_group', '708', 'termobele_malchiki', 'Термобелье для мальчиков', 178),
('product_group', '237', 'tolstovka_detskaya_devochki', 'Толстовка детская для девочек', 179),
('product_group', '236', 'tolstovka_detskaya_malchiki', 'Толстовка детская для мальчиков', 180),
('product_group', 'a88', 'tolstovka_molniya_devochki', 'Толстовка на молнии для девочек', 181),
('product_group', 'a82', 'tolstovka_molniya_malchiki', 'Толстовка на молнии для мальчиков', 182),
('product_group', 'a87', 'tolstovka_molniya_uteplennaya_devochki', 'Толстовка на молнии утепленная для девочек', 183),
('product_group', 'a86', 'tolstovka_bomber_devochki', 'Толстовка-бомбер для девочек', 184),
('product_group', 'a80', 'tolstovka_bomber_malchiki', 'Толстовка-бомбер для мальчиков', 185),
('product_group', 'a85', 'tolstovka_bomber_uteplennaya_devochki', 'Толстовка-бомбер утепленная для девочек', 186),
('product_group', 'a79', 'tolstovka_bomber_uteplennaya_malchiki', 'Толстовка-бомбер утепленная для мальчиков', 187),
('product_group', 'a84', 'tolstovka_hudi_devochki', 'Толстовка-худи для девочек', 188),
('product_group', 'a78', 'tolstovka_hudi_malchiki', 'Толстовка-худи для мальчиков', 189),
('product_group', 'a83', 'tolstovka_hudi_uteplennaya_devochki', 'Толстовка-худи утепленная для девочек', 190),
('product_group', 'a77', 'tolstovka_hudi_uteplennaya_malchiki', 'Толстовка-худи утепленная для мальчиков', 191),
('product_group', '955', 'top_detskiy_devochki', 'Топ детский для девочек', 192),
('product_group', 'a62', 'tregginsy_detskie_devochki', 'Треггинсы детские для девочек', 193),
('product_group', '171', 'trusy_detskie_devochki', 'Трусы детские для девочек', 194),
('product_group', '172', 'trusy_detskie_malchiki', 'Трусы детские для мальчиков', 195),
('product_group', 'a65', 'tunika_plyazhnaya_detskaya', 'Туника пляжная детская', 196),
('product_group', '217', 'ushki_mekhovye_detskie', 'Ушки меховые детские', 197),
('product_group', 'a60', 'futbolka_detskaya_devochki', 'Футболка детская для девочек', 198),
('product_group', '300', 'futbolka_detskaya_devochki_2', 'Футболка детская для девочек', 199),
('product_group', '310', 'futbolka_detskaya_malchiki', 'Футболка детская для мальчиков', 200),
('product_group', 'a74', 'futbolka_detskaya_novogodnyaya', 'Футболка детская новогодняя', 201),
('product_group', '883', 'futbolka_dlinnyy_rukav_devochki', 'Футболка длинный рукав детская для девочек', 202),
('product_group', '881', 'futbolka_dlinnyy_rukav_malchiki', 'Футболка длинный рукав детская для мальчиков', 203),
('product_group', '408', 'futbolka_dlinnyy_rukav_malenkogo_malchika', 'Футболка длинный рукав для маленького мальчика', 204),
('product_group', '450', 'futbolka_dlinnyy_rukav_malenkoy_devochki', 'Футболка длинный рукав для маленькой девочки', 205),
('product_group', '940', 'futbolka_malenkogo_malchika', 'Футболка для маленького мальчика', 206),
('product_group', '939', 'futbolka_malenkoy_devochki', 'Футболка для маленькой девочки', 207),
('product_group', '548', 'halat_detskiy_devochki', 'Халат детский для девочек', 208),
('product_group', '566', 'halat_detskiy_malchiki', 'Халат детский для мальчиков', 209),
('product_group', '578', 'tsarapki', 'Царапки', 210),
('product_group', '575', 'chepchik_novorozhdennykh', 'Чепчик для новорожденных', 211),
('product_group', '043', 'shapka_detskaya_demisezonnaya_devochki', 'Шапка детская демисезонная для девочек', 212),
('product_group', '044', 'shapka_detskaya_demisezonnaya_malchiki', 'Шапка детская демисезонная для мальчиков', 213),
('product_group', '219', 'shapka_zimnyaya_devochki', 'Шапка зимняя детская для девочек', 214),
('product_group', '220', 'shapka_zimnyaya_malchiki', 'Шапка зимняя детская для мальчиков', 215),
('product_group', '576', 'shapochka_novorozhdennykh', 'Шапочка для новорожденных', 216),
('product_group', '533', 'sharf_detskiy_devochki', 'Шарф детский для девочек', 217),
('product_group', '556', 'sharf_detskiy_malchiki', 'Шарф детский для мальчиков', 218),
('product_group', 'a54', 'shkolnye_bryuki_devochki', 'Школьные брюки для девочек', 219),
('product_group', '194', 'shorty_detskie_devochki', 'Шорты детские для девочек', 220),
('product_group', '193', 'shorty_detskie_malchiki', 'Шорты детские для мальчиков', 221),
('product_group', '965', 'shorty_malenkogo_malchika', 'Шорты для маленького мальчика', 222),
('product_group', '859', 'shorty_malenkoy_devochki', 'Шорты для маленькой девочки', 223),
('product_group', '900', 'shtanishki_malenkogo_malchika', 'Штанишки для маленького мальчика', 224),
('product_group', '573', 'shtanishki_malenkoy_devochki', 'Штанишки для маленькой девочки', 225),
('product_group', '290', 'shtany_detskie_devochki', 'Штаны детские для девочек', 226),
('product_group', '291', 'shtany_detskie_malchiki', 'Штаны детские для мальчиков', 227),
('product_group', '343', 'shtany_uteplennye_devochki', 'Штаны утепленные детские для девочек', 228),
('product_group', '879', 'shtany_uteplennye_malchiki', 'Штаны утепленные детские для мальчиков', 229),
('product_group', 'a69', 'yubka_vyazanaya_devochki', 'Юбка вязаная для девочек', 230),
('product_group', '302', 'yubka_detskaya_devochki', 'Юбка детская для девочек', 231),
('product_group', '691', 'yubka_malenkoy_devochki', 'Юбка для маленькой девочки', 232),
('product_group', '303', 'yubka_letnyaya_detskaya', 'Юбка летняя детская', 233),
('product_group', '367', 'yubka_shkolnaya_devochki', 'Юбка школьная для девочек', 234)
ON CONFLICT (category, value) DO UPDATE SET
  code = EXCLUDED.code,
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order;
