-- Удаляем все старые группы товаров
DELETE FROM reference_data WHERE category = 'product_group';

-- Вставляем все 144 группы товаров из списка
INSERT INTO reference_data (category, code, value, label, sort_order) VALUES
('product_group', '001', 'verxnyaya_odezhda_devochki', 'Верхняя одежда для девочек', 1),
('product_group', '002', 'verxnyaya_odezhda_malchiki', 'Верхняя одежда для мальчиков', 2),
('product_group', '003', 'verxnyaya_odezhda_novorozhdennye', 'Верхняя одежда для новорожденных', 3),
('product_group', '004', 'bryuki_kapri_shorty_yubki_devochki', 'Брюки, капри, шорты, юбки для девочек', 4),
('product_group', '005', 'bryuki_kapri_shorty_malchiki', 'Брюки, капри, шорты для мальчиков', 5),
('product_group', '006', 'kolgotki_devochki', 'Колготки для девочек', 6),
('product_group', '007', 'kolgotki_malchiki', 'Колготки для мальчиков', 7),
('product_group', '008', 'futbolki_mayki_topy_devochki', 'Футболки, майки, топы для девочек', 8),
('product_group', '009', 'futbolki_mayki_malchiki', 'Футболки, майки для мальчиков', 9),
('product_group', '010', 'rubashki_bluzki_devochki', 'Рубашки, блузки для девочек', 10),
('product_group', '011', 'rubashki_malchiki', 'Рубашки для мальчиков', 11),
('product_group', '012', 'dzhinsy_devochki', 'Джинсы для девочек', 12),
('product_group', '013', 'dzhinsy_malchiki', 'Джинсы для мальчиков', 13),
('product_group', '014', 'platya_sarafany_devochki', 'Платья, сарафаны для девочек', 14),
('product_group', '015', 'dzhempera_svitera_devochki', 'Джемпера, свитера для девочек', 15),
('product_group', '016', 'dzhempera_svitera_malchiki', 'Джемпера, свитера для мальчиков', 16),
('product_group', '017', 'tolstovki_hudi_kardigany_devochki', 'Толстовки, худи, кардиганы для девочек', 17),
('product_group', '018', 'tolstovki_hudi_kardigany_malchiki', 'Толстовки, худи, кардиганы для мальчиков', 18),
('product_group', '019', 'kombinezony_polukombinezony_devochki', 'Комбинезоны, полукомбинезоны для девочек', 19),
('product_group', '020', 'kombinezony_polukombinezony_malchiki', 'Комбинезоны, полукомбинезоны для мальчиков', 20),
('product_group', '021', 'kostyumy_devochki', 'Костюмы для девочек', 21),
('product_group', '022', 'kostyumy_malchiki', 'Костюмы для мальчиков', 22),
('product_group', '023', 'pizhamy_devochki', 'Пижамы для девочек', 23),
('product_group', '024', 'pizhamy_malchiki', 'Пижамы для мальчиков', 24),
('product_group', '025', 'noskorki_sledki_golfiki_devochki', 'Носочки, следки, гольфики для девочек', 25),
('product_group', '026', 'noskorki_sledki_golfiki_malchiki', 'Носочки, следки, гольфики для мальчиков', 26),
('product_group', '027', 'shapki_kepki_panamy_devochki', 'Шапки, кепки, панамы для девочек', 27),
('product_group', '028', 'shapki_kepki_panamy_malchiki', 'Шапки, кепки, панамы для мальчиков', 28),
('product_group', '029', 'sharfy_snudy_vareschki_perchatki_devochki', 'Шарфы, снуды, варежки, перчатки для девочек', 29),
('product_group', '030', 'sharfy_snudy_vareschki_perchatki_malchiki', 'Шарфы, снуды, варежки, перчатки для мальчиков', 30),
('product_group', '031', 'chulochno_nosochnye_izdeliya_novorozhdennye', 'Чулочно-носочные изделия для новорожденных', 31),
('product_group', '032', 'shapki_chepchiki_novorozhdennye', 'Шапки, чепчики для новорожденных', 32),
('product_group', '033', 'tsarapki_perchatki_novorozhdennye', 'Царапки, перчатки для новорожденных', 33),
('product_group', '034', 'kombinezony_polzunki_novorozhdennye', 'Комбинезоны, ползунки для новорожденных', 34),
('product_group', '035', 'raspashonki_kofty_novorozhdennye', 'Распашонки, кофты для новорожденных', 35),
('product_group', '036', 'pizhamy_novorozhdennye', 'Пижамы для новорожденных', 36),
('product_group', '037', 'polotentse_kupalnoe_novorozhdennye', 'Полотенце купальное для новорожденных', 37),
('product_group', '038', 'konvert_novorozhdennye', 'Конверт для новорожденных', 38),
('product_group', '039', 'bodiki_novorozhdennye', 'Бодики для новорожденных', 39),
('product_group', '040', 'slipy_trusy_plavki_muzhchiny', 'Слипы, трусы, плавки для мужчин', 40),
('product_group', '041', 'mayki_termobele_muzhchiny', 'Майки, термобелье для мужчин', 41),
('product_group', '042', 'futbolki_polo_muzhchiny', 'Футболки, поло для мужчин', 42),
('product_group', '043', 'rubashki_muzhchiny', 'Рубашки для мужчин', 43),
('product_group', '044', 'topy_mayki_zhenshchiny', 'Топы, майки для женщин', 44),
('product_group', '045', 'futbolki_polo_zhenshchiny', 'Футболки, поло для женщин', 45),
('product_group', '046', 'rubashki_tuniki_bluzki_zhenshchiny', 'Рубашки, туники, блузки для женщин', 46),
('product_group', '047', 'bele_zhenshchiny', 'Белье для женщин', 47),
('product_group', '048', 'sportivnoe_bele_zhenshchiny', 'Спортивное белье для женщин', 48),
('product_group', '049', 'kolgotki_chulki_leggings_zhenshchiny', 'Колготки, чулки, леггинсы для женщин', 49),
('product_group', '050', 'dzhinsy_dzhogger_chino_muzhchiny', 'Джинсы, джоггер, чино для мужчин', 50),
('product_group', '051', 'bryuki_shorty_muzhchiny', 'Брюки, шорты для мужчин', 51),
('product_group', '052', 'dzhinsy_zhenshchiny', 'Джинсы для женщин', 52),
('product_group', '053', 'bryuki_shorty_kapri_zhenshchiny', 'Брюки, шорты, капри для женщин', 53),
('product_group', '054', 'platya_sarafany_zhenshchiny', 'Платья, сарафаны для женщин', 54),
('product_group', '055', 'yubki_zhenshchiny', 'Юбки для женщин', 55),
('product_group', '056', 'svitshot_hudi_muzhchiny', 'Свитшот, худи для мужчин', 56),
('product_group', '057', 'dzhempera_svitera_muzhchiny', 'Джемпера, свитера для мужчин', 57),
('product_group', '058', 'svitshot_hudi_zhenshchiny', 'Свитшот, худи для женщин', 58),
('product_group', '059', 'dzhempera_svitera_zhilety_zhenshchiny', 'Джемпера, свитера, жилеты для женщин', 59),
('product_group', '060', 'verxnyaya_odezhda_muzhchiny', 'Верхняя одежда для мужчин', 60),
('product_group', '061', 'verxnyaya_odezhda_zhenshchiny', 'Верхняя одежда для женщин', 61),
('product_group', '062', 'kostyumy_muzhchiny', 'Костюмы для мужчин', 62),
('product_group', '063', 'kostyumy_zhenshchiny', 'Костюмы для женщин', 63),
('product_group', '064', 'noskorki_muzhchiny', 'Носочки для мужчин', 64),
('product_group', '065', 'noskorki_zhenshchiny', 'Носочки для женщин', 65),
('product_group', '066', 'pizhamy_domashnaya_odezhda_muzhchiny', 'Пижамы, домашняя одежда для мужчин', 66),
('product_group', '067', 'pizhamy_domashnaya_odezhda_zhenshchiny', 'Пижамы, домашняя одежда для женщин', 67),
('product_group', '068', 'kupalniki_pareo_zhenshchiny', 'Купальники, парео для женщин', 68),
('product_group', '069', 'shapki_kepki_panamy_muzhchiny', 'Шапки, кепки, панамы для мужчин', 69),
('product_group', '070', 'sharfy_snudy_perchatki_muzhchiny', 'Шарфы, снуды, перчатки для мужчин', 70),
('product_group', '071', 'shapki_kepki_panamy_zhenshchiny', 'Шапки, кепки, панамы для женщин', 71),
('product_group', '072', 'sharfy_snudy_perchatki_zhenshchiny', 'Шарфы, снуды, перчатки для женщин', 72),
('product_group', '073', 'sumki_ryukzaki', 'Сумки, рюкзаки', 73),
('product_group', '074', 'ochki_solntsezashchitnye', 'Очки солнцезащитные', 74),
('product_group', '075', 'remni_podtyazhki', 'Ремни, подтяжки', 75),
('product_group', '076', 'perchatki_vareschki_muzhchiny', 'Перчатки, варежки для мужчин', 76),
('product_group', '077', 'perchatki_vareschki_zhenshchiny', 'Перчатки, варежки для женщин', 77),
('product_group', '078', 'ukrasheniya', 'Украшения', 78),
('product_group', '079', 'zodvonki', 'Зонды', 79),
('product_group', '080', 'pledy_pokryvala', 'Пледы, покрывала', 80),
('product_group', '081', 'polotentsa', 'Полотенца', 81),
('product_group', '082', 'kedy_krossovki_devochki', 'Кеды, кроссовки для девочек', 82),
('product_group', '083', 'kedy_krossovki_malchiki', 'Кеды, кроссовки для мальчиков', 83),
('product_group', '084', 'tufli_mokasiny_balerinki_devochki', 'Туфли, мокасины, балеринки для девочек', 84),
('product_group', '085', 'tufli_mokasiny_malchiki', 'Туфли, мокасины для мальчиков', 85),
('product_group', '086', 'botinki_sapogi_devochki', 'Ботинки, сапоги для девочек', 86),
('product_group', '087', 'botinki_sapogi_malchiki', 'Ботинки, сапоги для мальчиков', 87),
('product_group', '088', 'tapochki_sandalii_shlepki_devochki', 'Тапочки, сандалии, шлепки для девочек', 88),
('product_group', '089', 'tapochki_sandalii_shlepki_malchiki', 'Тапочки, сандалии, шлепки для мальчиков', 89),
('product_group', '090', 'pinetki_devochki', 'Пинетки для девочек', 90),
('product_group', '091', 'pinetki_malchiki', 'Пинетки для мальчиков', 91),
('product_group', '092', 'kedy_krossovki_muzhchiny', 'Кеды, кроссовки для мужчин', 92),
('product_group', '093', 'tufli_mokasiny_muzhchiny', 'Туфли, мокасины для мужчин', 93),
('product_group', '094', 'botinki_sapogi_muzhchiny', 'Ботинки, сапоги для мужчин', 94),
('product_group', '095', 'tapochki_sandalii_muzhchiny', 'Тапочки, сандалии для мужчин', 95),
('product_group', '096', 'kedy_krossovki_zhenshchiny', 'Кеды, кроссовки для женщин', 96),
('product_group', '097', 'tufli_mokasiny_balerinki_zhenshchiny', 'Туфли, мокасины, балеринки для женщин', 97),
('product_group', '098', 'botinki_sapogi_zhenshchiny', 'Ботинки, сапоги для женщин', 98),
('product_group', '099', 'tapochki_sandalii_shlepki_zhenshchiny', 'Тапочки, сандалии, шлепки для женщин', 99),
('product_group', '100', 'sabo_zhenshchiny', 'Сабо для женщин', 100),
('product_group', '101', 'stelek_shnurki_shhetki', 'Стельки, шнурки, щетки', 101),
('product_group', '102', 'igrushki_myagkie', 'Игрушки мягкие', 102),
('product_group', '103', 'igrushki_razvivayushchie', 'Игрушки развивающие', 103),
('product_group', '104', 'igrushki_dlya_vannoy', 'Игрушки для ванной', 104),
('product_group', '105', 'postelnoe_bele_novorozhdennye', 'Постельное белье для новорожденных', 105),
('product_group', '106', 'postelnoe_bele_deti', 'Постельное белье для детей', 106),
('product_group', '107', 'odeyala_podushki_novorozhdennye', 'Одеяла, подушки для новорожденных', 107),
('product_group', '108', 'odeyala_podushki_deti', 'Одеяла, подушки для детей', 108),
('product_group', '109', 'postelnoe_bele_vzroslye', 'Постельное белье для взрослых', 109),
('product_group', '110', 'odeyala_podushki_vzroslye', 'Одеяла, подушки для взрослых', 110),
('product_group', '111', 'pokryvala_pledy', 'Покрывала, пледы', 111),
('product_group', '112', 'matrasy', 'Матрасы', 112),
('product_group', '113', 'navolochki_prostyni', 'Наволочки, простыни', 113),
('product_group', '114', 'polotentsa_kupalnye', 'Полотенца купальные', 114),
('product_group', '115', 'polotentsa_kuhonnye', 'Полотенца кухонные', 115),
('product_group', '116', 'fartuxi_prikhvatki', 'Фартухи, прихватки', 116),
('product_group', '117', 'shesterki_devochki', 'Шестерки для девочек', 117),
('product_group', '118', 'shesterki_malchiki', 'Шестерки для мальчиков', 118),
('product_group', '119', 'perchatki_futbolnye', 'Перчатки футбольные', 119),
('product_group', '120', 'myachi', 'Мячи', 120),
('product_group', '121', 'inventar_sportivnyy', 'Инвентарь спортивный', 121),
('product_group', '122', 'tualetnaya_bumaga', 'Туалетная бумага', 122),
('product_group', '123', 'salfetki_bumagnye', 'Салфетки бумажные', 123),
('product_group', '124', 'polotentsa_bumazhnye', 'Полотенца бумажные', 124),
('product_group', '125', 'kosmetika', 'Косметика', 125),
('product_group', '126', 'gigena', 'Гигиена', 126),
('product_group', '127', 'tovary_dlya_doma', 'Товары для дома', 127),
('product_group', '128', 'kancelyariya', 'Канцелярия', 128),
('product_group', '129', 'posuda', 'Посуда', 129),
('product_group', '130', 'bytovaya_khimiya', 'Бытовая химия', 130),
('product_group', '131', 'ukrasheniya_devochki', 'Украшения для девочек', 131),
('product_group', '132', 'ukrasheniya_zhenshchiny', 'Украшения для женщин', 132),
('product_group', '133', 'bижутерия', 'Бижутерия', 133),
('product_group', '134', 'ochki_solntsezashchitnye_deti', 'Очки солнцезащитные для детей', 134),
('product_group', '135', 'ochki_solntsezashchitnye_vzroslye', 'Очки солнцезащитные для взрослых', 135),
('product_group', '136', 'kanctovary', 'Канцтовары', 136),
('product_group', '137', 'igrushki', 'Игрушки', 137),
('product_group', '138', 'nabory_tvorcheskie', 'Наборы творческие', 138),
('product_group', '139', 'tetradi_bloknoty', 'Тетради, блокноты', 139),
('product_group', '140', 'ruchki_karandashi', 'Ручки, карандаши', 140),
('product_group', '141', 'shkolnye_tovary', 'Школьные товары', 141),
('product_group', '142', 'sumki_dlya_obuvi', 'Сумки для обуви', 142),
('product_group', '143', 'ryukzaki_shkolnye', 'Рюкзаки школьные', 143),
('product_group', '144', 'penaly', 'Пеналы', 144)
ON CONFLICT (category, value) DO UPDATE SET
  code = EXCLUDED.code,
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order;
